# Generated by Django 5.0.2 on 2024-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransacaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco_origem", models.CharField(max_length=100)),
                ("agencia_origem", models.CharField(max_length=20)),
                ("conta_origem", models.CharField(max_length=20)),
                ("banco_destino", models.CharField(max_length=100)),
                ("agencia_destino", models.CharField(max_length=20)),
                ("conta_destino", models.CharField(max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_hora", models.DateTimeField()),
            ],
        ),
    ]
